name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE_NAME }}
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.SERVICE_NAME }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --update-env-vars GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
